/**
 * Seed the garden with initial plants
 *
 * This script creates initial plants with:
 * - Quantum circuit records (placeholder definitions)
 * - Variant assignments based on rarity weights
 * - Positions distributed across the canvas
 * - Lifecycle state (germinated or dormant)
 *
 * Run with: pnpm db:seed
 */

import { PrismaClient } from "@prisma/client";
import { PLANT_VARIANTS, selectColorVariation } from "@quantum-garden/shared";

const db = new PrismaClient();

// Canvas dimensions (match CANVAS constants)
const CANVAS_WIDTH = 1200;
const CANVAS_HEIGHT = 800;

// Seed configuration
const NUM_PLANTS = 12;
const MARGIN = 80; // Keep plants away from edges

/**
 * Select a variant based on rarity weights.
 * Higher rarity = more likely to be selected.
 */
function selectVariant(): (typeof PLANT_VARIANTS)[number] {
  if (PLANT_VARIANTS.length === 0) {
    throw new Error("No plant variants defined");
  }

  const totalWeight = PLANT_VARIANTS.reduce((sum, v) => sum + v.rarity, 0);
  let random = Math.random() * totalWeight;

  for (const variant of PLANT_VARIANTS) {
    random -= variant.rarity;
    if (random <= 0) {
      return variant;
    }
  }

  // Fallback to first variant (guaranteed to exist due to check above)
  return PLANT_VARIANTS[0]!;
}

/**
 * Generate a random position within the canvas.
 * Uses a grid-based distribution to avoid overlapping.
 */
function generatePositions(count: number): { x: number; y: number }[] {
  const positions: { x: number; y: number }[] = [];
  const usableWidth = CANVAS_WIDTH - 2 * MARGIN;
  const usableHeight = CANVAS_HEIGHT - 2 * MARGIN;

  // Calculate grid dimensions
  const cols = Math.ceil(Math.sqrt(count * (usableWidth / usableHeight)));
  const rows = Math.ceil(count / cols);
  const cellWidth = usableWidth / cols;
  const cellHeight = usableHeight / rows;

  for (let i = 0; i < count; i++) {
    const col = i % cols;
    const row = Math.floor(i / cols);

    // Center of cell with some random jitter
    const jitterX = (Math.random() - 0.5) * cellWidth * 0.5;
    const jitterY = (Math.random() - 0.5) * cellHeight * 0.5;

    positions.push({
      x: MARGIN + cellWidth * (col + 0.5) + jitterX,
      y: MARGIN + cellHeight * (row + 0.5) + jitterY,
    });
  }

  return positions;
}

/**
 * Create a placeholder quantum circuit definition.
 * In production, this would be generated by the quantum service.
 */
function createPlaceholderCircuit(seed: number): string {
  // Base64 encoded placeholder (represents a simple circuit)
  // This will be replaced with real Qiskit circuit definitions
  const placeholder = {
    type: "placeholder",
    seed,
    num_qubits: 5,
    created_at: new Date().toISOString(),
  };
  return Buffer.from(JSON.stringify(placeholder)).toString("base64");
}

async function main() {
  console.log("Seeding garden...");

  // Clear existing plants and quantum records
  console.log("Clearing existing data...");
  await db.observationEvent.deleteMany({});
  await db.plant.deleteMany({});
  await db.quantumRecord.deleteMany({});
  await db.observationRegion.deleteMany({});
  await db.entanglementGroup.deleteMany({});

  // Generate positions
  const positions = generatePositions(NUM_PLANTS);

  console.log(`Creating ${NUM_PLANTS} plants...`);

  for (let i = 0; i < NUM_PLANTS; i++) {
    const variant = selectVariant();
    const position = positions[i]!;
    const seed = Date.now() + i;

    // Create quantum record first
    const quantumRecord = await db.quantumRecord.create({
      data: {
        circuitDefinition: createPlaceholderCircuit(seed),
        status: "pending",
        measurements: [],
        probabilities: [],
      },
    });

    // Determine if plant should start germinated
    // 50% of plants start germinated for immediate visual interest
    const shouldGerminate = Math.random() < 0.5;
    const germinatedAt = shouldGerminate ? new Date() : null;

    // Select color variation for multi-color variants
    // selectColorVariation takes variant and probability, returns variation name or null
    const colorVariationName = selectColorVariation(variant, Math.random());

    // Random lifecycle modifier (0.8 - 1.2 speed variation)
    const lifecycleModifier = 0.8 + Math.random() * 0.4;

    // Create plant
    const plant = await db.plant.create({
      data: {
        positionX: position.x,
        positionY: position.y,
        observed: false,
        visualState: "superposed",
        quantumCircuitId: quantumRecord.id,
        variantId: variant.id,
        germinatedAt,
        lifecycleModifier,
        colorVariationName,
      },
    });

    console.log(
      `  Created plant ${i + 1}/${NUM_PLANTS}: ${variant.name} at (${position.x.toFixed(0)}, ${position.y.toFixed(0)})${germinatedAt ? " [germinated]" : " [dormant]"}`
    );
  }

  console.log("\nGarden seeded successfully!");
  console.log(`  Total plants: ${NUM_PLANTS}`);

  // Print variant distribution
  const plants = await db.plant.findMany();
  const variantCounts = new Map<string, number>();
  for (const plant of plants) {
    variantCounts.set(plant.variantId, (variantCounts.get(plant.variantId) ?? 0) + 1);
  }
  console.log("  Variant distribution:");
  for (const [variantId, count] of variantCounts) {
    console.log(`    - ${variantId}: ${count}`);
  }
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
