/**
 * Client for the Quantum Garden quantum service.
 *
 * Provides methods to:
 * - List available circuit types
 * - Generate circuits based on seed and rarity
 * - Execute circuits and get resolved traits
 */

import type {
  CircuitMetadata,
  GenerateCircuitRequest,
  GenerateCircuitResponse,
  JobStatsResponse,
  JobStatusResponse,
  ListCircuitsResponse,
  MeasureCircuitRequest,
  MeasureCircuitResponse,
  QuantumPool,
  SubmitJobRequest,
  SubmitJobResponse,
} from "@quantum-garden/shared";

/**
 * Get the quantum service URL from environment.
 * Falls back to localhost for development.
 */
function getQuantumServiceUrl(): string {
  return process.env.QUANTUM_SERVICE_URL ?? "http://localhost:18742";
}

/**
 * List all registered quantum circuits.
 *
 * Returns metadata for each available circuit type, useful for
 * educational documentation and UI selection.
 */
export async function listCircuits(): Promise<ListCircuitsResponse> {
  const url = `${getQuantumServiceUrl()}/circuits/`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to list circuits: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Get metadata for a specific circuit type.
 *
 * @param circuitId - The circuit identifier (e.g., "superposition")
 */
export async function getCircuit(circuitId: string): Promise<CircuitMetadata> {
  const url = `${getQuantumServiceUrl()}/circuits/${circuitId}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to get circuit ${circuitId}: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Generate a quantum circuit for a plant.
 *
 * The circuit can be generated by:
 * - Explicit circuit type (circuitId)
 * - Plant variant rarity (rarity) - auto-selects appropriate complexity
 *
 * @param request - Generation parameters
 * @returns Circuit definition and metadata
 */
export async function generateCircuit(
  request: GenerateCircuitRequest
): Promise<GenerateCircuitResponse> {
  const url = `${getQuantumServiceUrl()}/circuits/generate`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      seed: request.seed,
      circuit_id: request.circuitId,
      rarity: request.rarity,
    }),
  });

  if (!response.ok) {
    throw new Error(`Failed to generate circuit: ${response.statusText}`);
  }

  const data = await response.json();

  return {
    circuitId: data.circuit_id,
    circuitDefinition: data.circuit_definition,
    numQubits: data.num_qubits,
    level: data.level,
    concept: data.concept,
  };
}

/**
 * Measure a plant's quantum circuit and resolve traits.
 *
 * This is the main function called during observation. It:
 * 1. Executes the circuit (using configured mode: mock/simulator/hardware)
 * 2. Maps measurements to visual traits using the circuit's mapper
 *
 * @param request - Measurement parameters
 * @returns Resolved traits or error
 */
export async function measureCircuit(
  request: MeasureCircuitRequest
): Promise<MeasureCircuitResponse> {
  const url = `${getQuantumServiceUrl()}/circuits/measure`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      plant_id: request.plantId,
      circuit_definition: request.circuitDefinition,
      circuit_id: request.circuitId,
      shots: request.shots,
    }),
  });

  if (!response.ok) {
    throw new Error(`Failed to measure circuit: ${response.statusText}`);
  }

  const data = await response.json();

  return {
    plantId: data.plant_id,
    success: data.success,
    traits: data.traits
      ? {
          glyphPattern: data.traits.glyphPattern,
          colorPalette: data.traits.colorPalette,
          growthRate: data.traits.growthRate,
          opacity: data.traits.opacity,
        }
      : undefined,
    executionMode: data.execution_mode,
    error: data.error,
  };
}

/**
 * Get the appropriate circuit for a given plant variant rarity.
 *
 * This is a convenience function that generates a circuit based on rarity.
 * Higher rarity (common plants) → simpler circuits
 * Lower rarity (rare plants) → more complex circuits
 *
 * @param seed - Random seed for deterministic generation
 * @param rarity - Plant variant rarity (0.0 to 1.3+)
 */
export async function generateCircuitForRarity(
  seed: number,
  rarity: number
): Promise<GenerateCircuitResponse> {
  return generateCircuit({ seed, rarity });
}

/**
 * Execute a raw circuit without trait mapping.
 *
 * Useful for testing and debugging circuits.
 *
 * @param circuitDefinition - Base64 encoded circuit
 * @param shots - Number of measurement shots
 * @param mode - Execution mode override (optional)
 */
export async function executeCircuit(
  circuitDefinition: string,
  shots: number = 100,
  mode?: "mock" | "simulator" | "hardware"
): Promise<{
  success: boolean;
  measurements?: number[];
  counts?: Record<string, number>;
  probabilities?: Record<string, number>;
  executionMode?: string;
  error?: string;
}> {
  const url = `${getQuantumServiceUrl()}/circuits/execute`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      circuit_definition: circuitDefinition,
      shots,
      mode,
    }),
  });

  if (!response.ok) {
    throw new Error(`Failed to execute circuit: ${response.statusText}`);
  }

  const data = await response.json();

  return {
    success: data.success,
    measurements: data.measurements,
    counts: data.counts,
    probabilities: data.probabilities,
    executionMode: data.execution_mode,
    error: data.error,
  };
}

// =============================================================================
// Async Job API
// =============================================================================

/**
 * Submit a quantum measurement job.
 *
 * Jobs are processed asynchronously by the quantum service.
 * Use getJobStatus() or waitForJob() to check completion.
 *
 * @param request - Job submission parameters
 * @returns Job ID and initial status
 */
export async function submitJob(request: SubmitJobRequest): Promise<SubmitJobResponse> {
  const url = `${getQuantumServiceUrl()}/jobs/submit`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      plant_id: request.plantId,
      circuit_id: request.circuitId,
      rarity: request.rarity,
      seed: request.seed,
      shots: request.shots,
    }),
  });

  if (!response.ok) {
    throw new Error(`Failed to submit job: ${response.statusText}`);
  }

  const data = await response.json();

  return {
    jobId: data.job_id,
    status: data.status,
    circuitId: data.circuit_id,
    executionMode: data.execution_mode,
  };
}

/**
 * Get the status and results of a job.
 *
 * @param jobId - The job ID from submitJob()
 * @returns Job status and traits (if completed)
 */
export async function getJobStatus(jobId: string): Promise<JobStatusResponse> {
  const url = `${getQuantumServiceUrl()}/jobs/${jobId}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to get job status: ${response.statusText}`);
  }

  const data = await response.json();

  return {
    jobId: data.job_id,
    plantId: data.plant_id,
    circuitId: data.circuit_id,
    status: data.status,
    createdAt: data.created_at,
    submittedAt: data.submitted_at,
    completedAt: data.completed_at,
    executionMode: data.execution_mode,
    traits: data.traits,
    error: data.error,
  };
}

/**
 * Wait for a job to complete.
 *
 * Blocks until the job completes or times out.
 *
 * @param jobId - The job ID from submitJob()
 * @param timeout - Maximum seconds to wait (default 30, max 120)
 * @returns Completed job status with traits
 */
export async function waitForJob(jobId: string, timeout: number = 30): Promise<JobStatusResponse> {
  const url = `${getQuantumServiceUrl()}/jobs/${jobId}/wait?timeout=${timeout}`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to wait for job: ${response.statusText}`);
  }

  const data = await response.json();

  return {
    jobId: data.job_id,
    plantId: data.plant_id,
    circuitId: data.circuit_id,
    status: data.status,
    createdAt: data.created_at,
    submittedAt: data.submitted_at,
    completedAt: data.completed_at,
    executionMode: data.execution_mode,
    traits: data.traits,
    error: data.error,
  };
}

/**
 * Get job queue statistics.
 *
 * @returns Statistics about pending, running, and completed jobs
 */
export async function getJobStats(): Promise<JobStatsResponse> {
  const url = `${getQuantumServiceUrl()}/jobs/`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to get job stats: ${response.statusText}`);
  }

  return response.json();
}

// =============================================================================
// Quantum Result Pool API
// =============================================================================

/**
 * Get the pre-computed quantum result pool.
 *
 * The pool contains pre-computed quantum measurement results for all circuit types.
 * Results are selected deterministically based on plant ID for instant trait revelation.
 *
 * @returns The complete quantum pool with all results
 */
export async function getQuantumPool(): Promise<QuantumPool> {
  const url = `${getQuantumServiceUrl()}/circuits/pool`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to get quantum pool: ${response.statusText}`);
  }

  return response.json();
}
